packages:
  - dashboard

allowBuilds:
  "@google/genai": false
  baileys: false
  esbuild: true
  ffmpeg-static: false
  msgpackr-extract: false
  protobufjs: false
  sharp: false
  youtube-dl-exec: false
